// AUTH CONSTANTS
export const CRS_TOKEN = "crsToken";
export const SET_CRS_TOKEN = "SET_CRS_TOKEN";
export const APPLICATION_INIT = "APPLICATION_INIT";
export const WIPE_CURRENT_DATA = "WIPE_CURRENT_DATA";

// LOGIN CONSTANTS
export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const SET_USER_PROFILE = "SET_USER_PROFILE";
export const USER_SIGN_OUT = "USER_SIGN_OUT";

// CONFERENCE CONSTANTS
export const CONFERENCE_SEARCH = "CONFERENCE_SEARCH";
export const USER_CONFERENCE_SEARCH = "USER_CONFERENCE_SEARCH";
export const IS_LOADING = "IS_LOADING";
export const IS_SAVING = "IS_SAVING";
export const DATA_CHANGED = "DATA_CHANGED";
export const GET_CURRENT_CONFERENCE = "GET_CURRENT_CONFERENCE";
export const GET_CURRENT_REGISTRANT = "GET_CURRENT_REGISTRANT";
export const UPDATE_CURRENT_REGISTRANT = "UPDATE_CURRENT_REGISTRANT";
export const DELETE_CURRENT_REGISTRANT = "DELETE_CURRENT_REGISTRANT";
export const STAFF_SEARCH = "STAFF_SEARCH";
